service: restaurante-serverless

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: local
  lambdaHashingVersion: 20201221

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566

functions:
  criarPedido:
    handler: src/lambdas/createOrder.handler
    events:
      - http:
          path: pedidos
          method: post

  processarPedido:
    handler: src/lambdas/processOrder.handler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:000000000000:pedidos-queue

resources:
  Resources:
    PedidosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Pedidos
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    PedidosQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: pedidos-queue

    PedidosBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: pedidos-pdfs

    PedidosTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: PedidosConcluidos

    SNSPedidosQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: sns-notificacoes-pedidos

    SNSPedidosToQueueSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: !Ref PedidosTopic
        RawMessageDelivery: true
        Protocol: sqs
        Endpoint: !GetAtt SNSPedidosQueue.Arn
